# -*- coding: utf-8 -*-
"""readaloud_text 단위테스트.  실행: python -m unittest discover -s tests  (프로젝트 폴더에서)

GOLDEN 은 크롬 확장 read-aloud-hrg HEAD(afae39a)의 JS 함수를 node 로 직접 돌려 얻은 값이다
(player.js:81 → document.js preprocess → speech.js Speech()/getChunks/CharBreaker → spoken-text.js makeSpokenText,
 page-ui-host.js alignSegmentsToSource). 오프셋은 JS 의 UTF-16 값을 파이썬 코드 포인트로 환산했다.
영어 단어 목록은 전체(850KB) 대신 MINI_WORDS 를 JS·파이썬 양쪽에 똑같이 넣었다("none" = 빈 목록).
HAND_CASES·GOLDEN 은 저장소 밖 대조 도구(scratchpad node_golden/hand_cases.py, make_expected.py)가 만든 것을
그대로 옮겼다 — 손으로 고치지 말고 그 도구로 다시 만든다.
"""
import hashlib
import json
import os
import random
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import readaloud_text as rt  # noqa: E402

MINI_WORDS = {w: 10 for w in [
    "read", "change", "log", "page", "host", "node", "modules", "align", "segments", "source", "not", "edit",
    "progress", "player", "don't", "know", "file", "this", "see", "and", "are", "updated", "returns", "results",
    "the", "quick", "brown", "fox", "jumps", "config", "user", "run",
]}

LONG_KO = ("가나다라마바사아자차카타파하 " * 60).strip()           # 공백 있는 긴 줄(>750)
LONG_KO_SENT = "이것은 아주 긴 문장입니다. " * 50                   # 문장 여러 개가 한 줄(>750)
LONG_EN = "The quick brown fox jumps over the lazy dog, again and again; " * 15
LONG_NOSPACE = "가" * 800 + "끝"                                      # 공백 없는 긴 덩어리
LONG_EMOJI_NOSPACE = "😀가" * 300                                      # 이모지 섞인 공백 없는 덩어리

HAND_CASES = [
    {"name": "ko_bullets", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "오늘 회의 요약\n- 첫째, 일정 확인\n- 둘째: 예산 2,200만 원 승인\n\n다음 단계 → 배포 → 모니터링"},
    {"name": "en_code_names", "lang": "en-US", "words": MINI_WORDS,
     "text": "README and CHANGELOG are updated.\nDO NOT EDIT this file.\nSee page-ui-host.js and node_modules/foo.\n"
             "alignSegmentsToSource returns APIs results.\nI DON'T know."},
    {"name": "ko_voice_code_names", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "page-ui-host.js 파일과 node_modules 폴더, README 를 보세요. IN_PROGRESS 상태입니다."},
    {"name": "urls", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "자세한 내용은 https://example.com/a/b?c=1 참고\n링크2: http://x.y/z😀 끝"},
    {"name": "emoji_repeat", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "좋아요 😀😀😀😀 정말!!!!! ㅋㅋㅋㅋㅋ\n🎉 축하합니다 🎉\n👍🏽 ❤️ 1111111"},
    {"name": "markdown", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "# 제목\n**굵게** 그리고 *기울임*\n> 인용문\n```python\nprint('hi')\n```\n| a | b |\n|---|---|\n---"},
    {"name": "blank_crlf", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "\r\n\r\n  첫 줄  \r\n\r\n\r\n둘째 줄\r\n   \r\n"},
    {"name": "short_lines_ko", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "\n".join(["가", "나", "다", "라", "마", "바", "사", "아", "자", "차", "카", "타", "파", "하",
                        "가나다라마바사아자차카타파하가나다라마바사", "끝"])},
    {"name": "short_lines_en", "lang": "en-US", "words": MINI_WORDS,
     "text": "a\nb\nc\nThis line is long enough to stand on its own as a segment of text.\nd\ne"},
    {"name": "arrows", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "A -> B --> C ⇒ D ➡️ E\n동남아 → 일본\n(→ 다음)\n→ 시작\n끝 →\n가 → → 나"},
    {"name": "slashes", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "알류샨/알래스카, UI/UX, 9/27, and/or, 1/2 컵, a / b, js/player.js, /usr/bin, ~/.ssh, ./run.sh"},
    {"name": "thousands_ko", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "2,200원, 1,000,000명, 12,345.67, 1,2,3 목록, 3,000"},
    {"name": "thousands_en", "lang": "en-US", "words": MINI_WORDS,
     "text": "2,200 dollars, 1,000,000 people, 12,345.67, 1,2,3 list"},
    {"name": "stars", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "**“중요”** 2**3 a ** b ***끝***"},
    {"name": "numbered", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "1. 첫째\n2. 둘째\n3) 셋째\n• 불릿\n* 별 불릿"},
    {"name": "spaces", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "가 나 다\t라​마﻿바"},
    {"name": "latin_edge", "lang": "en-US", "words": MINI_WORDS,
     "text": "café README résumé naïve RÉSUMÉ config.json user's USER'S"},
    {"name": "mixed_en_punctuator", "lang": "en-US", "voiceLang": "ko-KR", "words": MINI_WORDS,
     "text": "Dr. Kim met Mr. Lee at 3 p.m. 그리고 회의를 했다. U.S. Inc. results."},
    {"name": "long_ko", "lang": "ko-KR", "words": MINI_WORDS, "text": "앞줄\n" + LONG_KO + "\n뒷줄"},
    {"name": "long_ko_sentences", "lang": "ko-KR", "words": MINI_WORDS, "text": LONG_KO_SENT},
    {"name": "long_en", "lang": "en-US", "words": MINI_WORDS, "text": LONG_EN},
    {"name": "long_nospace", "lang": "ko-KR", "words": MINI_WORDS, "text": LONG_NOSPACE},
    {"name": "long_nospace_en", "lang": "en-US", "words": MINI_WORDS, "text": "x" * 1600},
    {"name": "long_emoji_nospace", "lang": "ko-KR", "words": MINI_WORDS, "text": LONG_EMOJI_NOSPACE},
    {"name": "empty", "lang": "ko-KR", "words": MINI_WORDS, "text": ""},
    {"name": "only_spaces", "lang": "ko-KR", "words": MINI_WORDS, "text": "   "},
    {"name": "only_newlines", "lang": "ko-KR", "words": MINI_WORDS, "text": "\n\n\n"},
    {"name": "no_words", "lang": "en-US", "words": "none",
     "text": "README and CHANGELOG, alignSegmentsToSource, DO NOT EDIT"},
    # 확장 쪽 버릇: 라틴 규칙에서 750자 넘는 구가 단어로 쪼개질 때 구 첫머리 '/' 가 사라져 정렬 전체가 null
    {"name": "latin_leading_slash_quirk", "lang": "en-US", "words": MINI_WORDS,
     "text": "첫 줄\na, /" + "word " * 160},
    # ── 적대적 입력(2차 검증 추가, 확장 afae39a 기준) ──
    # afae39a: 한국어 음성은 두 글자 대문자를 떼어 읽힌다(VS → "V S"), 두 글자 복수형(PCs)은 그대로
    {"name": "ko_two_capitals", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "VS Code 와 PCs, IDs, UI/UX, TCP/IP, GPT-4, js 파일, x.js, ok.ui, AI 가 IT 를"},
    {"name": "en_two_capitals", "lang": "en-US", "words": MINI_WORDS,
     "text": "VS Code and PCs, IDs, UI/UX, TCP/IP, GPT-4, js file, x.js, ok.ui, AI and IT"},
    {"name": "combining_marks", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "café RÉSUMÉ á́́́́ 각각 끝"},
    {"name": "zwj_flags", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "👨‍👩‍👧‍👦 가족 🇰🇷🇰🇷 국기 1️⃣ 첫째 👍🏽👍🏽👍🏽👍🏽 끝"},
    # 줄 분리는 \n 만: \r 단독·U+2028·U+2029·VT·FF 는 같은 줄 안의 공백
    {"name": "cr_only_separators", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "첫째\r둘째 셋째 넷째\x0b다섯\x0c여섯\n일곱"},
    # 공백도 반복 문자 규칙을 받는다(4개 이상 → 3개)
    {"name": "tabs_spaces", "lang": "ko-KR", "words": MINI_WORDS,
     "text": "가\t\t\t\t\t나          다　　　　라"},
    # 공백 없는 750(UTF-16)자 줄: 붙인 마침표 하나가 따로 조각이 되고 그 조각의 원문 구간은 없다(확장도 같음)
    {"name": "exact_750_nospace", "lang": "en-US", "words": MINI_WORDS, "text": "ab" * 375},
    {"name": "exact_750_nospace_ko", "lang": "ko-KR", "words": MINI_WORDS, "text": "가나" * 375},
    {"name": "long_digits", "lang": "ko-KR", "words": MINI_WORDS, "text": "1234567890" * 80},
    {"name": "long_url", "lang": "ko-KR", "words": MINI_WORDS, "text": "앞 https://" + "ab" * 400 + " 뒤"},
    {"name": "only_ws_variety", "lang": "ko-KR", "words": MINI_WORDS, "text": " \t　﻿"},
    # 확장 버릇 (a)의 흔한 모양: 750자 넘는 영어 불릿 줄은 머리의 "- " 가 빠져 형광펜 전체가 None
    {"name": "en_long_bullet_quirk", "lang": "en-US", "words": MINI_WORDS, "text": "짧은 줄\n- " + "word " * 160},
]

GOLDEN = {'ko_bullets': {'ranges': [(0, 41), (43, 60)],
                'spoken_sha1': '5be8b7e625a5fbf1d5f9c1807b038ffac9cb2fe9',
                'alignment_null': False,
                'segments_sha1': '5f5ee15ba69ee7cdadcc9ef550662c78373b73da',
                'source_index_sha1': '1caa299ecceef1bcd4fa321c17b3d95b044ff67f',
                'spoken': ['오늘 회의 요약.\n\n- 첫째, 일정 확인.\n\n- 둘째: 예산 2200만 원 승인.\n\n',
                           '다음 단계.\u2003배포.\u2003모니터링.']},
 'en_code_names': {'ranges': [(0, 98), (99, 156)],
                   'spoken_sha1': '28dc3d9f02bad9a83db7dd9f9a58ef413d6df90f',
                   'alignment_null': False,
                   'segments_sha1': 'e05ca68503d61b348bde53aa719761a593ea8aac',
                   'source_index_sha1': 'ff643ff29fe0431d070ebab96e48d5642816d73f',
                   'spoken': ['read me and change log are updated.\n'
                              '\n'
                              'do not edit this file.\n'
                              '\n'
                              'See page dash UI dash host dot JS and node underscore modules slash foo.\n'
                              '\n',
                              "align Segments To Source returns APIs results.\n\nI don't know."]},
 'ko_voice_code_names': {'ranges': [(0, 69)],
                         'spoken_sha1': 'f1731832711883fe8a08c4ef88416e18d19ea037',
                         'alignment_null': False,
                         'segments_sha1': 'ffa76b3a423f414fa0d2bf103b943a3bb159a236',
                         'source_index_sha1': '8696eba6e676368f79bf4e5eb82ebb83391e01a7',
                         'spoken': ['page 대시 U I 대시 host 쩜 J S 파일과 node 언더바 modules 폴더, read me 를 보세요. in '
                                    '언더바 progress 상태입니다.']},
 'urls': {'ranges': [(0, 59)],
          'spoken_sha1': '62cc76f6b5a64bdaf2d4decf754ce64e127b648f',
          'alignment_null': False,
          'segments_sha1': '62cc76f6b5a64bdaf2d4decf754ce64e127b648f',
          'source_index_sha1': '55d9d3fb58378b7844bc628de637cd534f9d01c4',
          'spoken': ['자세한 내용은 HTTP URL. 참고.\n\n링크2: HTTP URL. 끝.']},
 'emoji_repeat': {'ranges': [(0, 32), (33, 46)],
                  'spoken_sha1': '2185313afd6433ea50c0bf0d6311d7cfcaa4adaa',
                  'alignment_null': False,
                  'segments_sha1': '2185313afd6433ea50c0bf0d6311d7cfcaa4adaa',
                  'source_index_sha1': 'b769b4947fd7b2a3bd33c8cb409ad2bb78aeed96',
                  'spoken': ['좋아요 😀😀😀😀 정말!!! ㅋㅋㅋ.\n\n🎉 축하합니다 🎉.\n\n', '👍🏽 ❤️ 1111111.']},
 'markdown': {'ranges': [(0, 49), (50, 77)],
              'spoken_sha1': '185ce4c07ae14b5de1246e4e47a16a279de9683d',
              'alignment_null': False,
              'segments_sha1': '26e6d807f2a7bbc36c09e63530dd8611db92dc42',
              'source_index_sha1': '0bf7d40649a56c666ce88012205086acd03a7e3f',
              'spoken': ["# 제목.\n\n굵게 그리고 *기울임*.\n\n> 인용문.\n\n```python.\n\nprint('hi').\n\n",
                         '```.\n\n| a | b |.\n\n|---|---|.\n\n---.']},
 'blank_crlf': {'ranges': [(6, 21)],
                'spoken_sha1': '6be14830a9599d216e8c9490ed299b89c9b5f07b',
                'alignment_null': False,
                'segments_sha1': '6be14830a9599d216e8c9490ed299b89c9b5f07b',
                'source_index_sha1': '479a75de50a8b40f4bd5c989ebab229bb483c432',
                'spoken': ['\n\n첫 줄.\n\n둘째 줄.\n\n']},
 'short_lines_ko': {'ranges': [(0, 49), (50, 51)],
                    'spoken_sha1': '94f685cd906ceb5c69a351b450511f7388a1427c',
                    'alignment_null': False,
                    'segments_sha1': '94f685cd906ceb5c69a351b450511f7388a1427c',
                    'source_index_sha1': '2d60062ab4b2b8c14aea20d3958ec098f92e9363',
                    'spoken': ['가.\n'
                               '\n'
                               '나.\n'
                               '\n'
                               '다.\n'
                               '\n'
                               '라.\n'
                               '\n'
                               '마.\n'
                               '\n'
                               '바.\n'
                               '\n'
                               '사.\n'
                               '\n'
                               '아.\n'
                               '\n'
                               '자.\n'
                               '\n'
                               '차.\n'
                               '\n'
                               '카.\n'
                               '\n'
                               '타.\n'
                               '\n'
                               '파.\n'
                               '\n'
                               '하.\n'
                               '\n'
                               '가나다라마바사아자차카타파하가나다라마바사.\n'
                               '\n',
                               '끝.']},
 'short_lines_en': {'ranges': [(0, 76)],
                    'spoken_sha1': '49f8bcd6fd195f8943dfa35b3014d7f180cd9d7d',
                    'alignment_null': False,
                    'segments_sha1': '49f8bcd6fd195f8943dfa35b3014d7f180cd9d7d',
                    'source_index_sha1': 'b0fad21eea7bd36532f6c9dcb1c18d78252c9bc8',
                    'spoken': ['a.\n'
                               '\n'
                               'b.\n'
                               '\n'
                               'c.\n'
                               '\n'
                               'This line is long enough to stand on its own as a segment of text.\n'
                               '\n'
                               'd.\n'
                               '\n'
                               'e.']},
 'arrows': {'ranges': [(0, 46), (47, 54)],
            'spoken_sha1': '1c48a4ac8974554dd60d59e7c543464cae28933c',
            'alignment_null': False,
            'segments_sha1': 'b860c53cb977f3af9ae406ef3d8d85ae79d440b4',
            'source_index_sha1': 'e2769bb77265112041a7c3abca6e2c19f479f561',
            'spoken': ['A.\u2003B.\u2003C.\u2003D.\u2003E.\n\n동남아.\u2003일본.\n\n(다음).\u2003시작.\n\n끝.\n\n',
                       '가.\u2003나.']},
 'slashes': {'ranges': [(0, 85)],
             'spoken_sha1': '50a2b2f61808c7776fe1f6d6403b19c294fd08ca',
             'alignment_null': False,
             'segments_sha1': '6121beaac29c0e285b0d2f4531fad60d247ddea8',
             'source_index_sha1': 'd44d7d10468b930873b28e4b0aa566164b5dce3b',
             'spoken': ['알류샨, 알래스카, U I, U X, 9/27, and, or, 1/2 컵, a, b, J S 슬래시 player 쩜 J S, 슬래시 usr 슬래시 '
                        'bin, ~슬래시 쩜 SSH, 쩜 슬래시 run 쩜 S H.']},
 'thousands_ko': {'ranges': [(0, 46)],
                  'spoken_sha1': '50ae8b6a99c363e2af57081a53ba580ed81b2485',
                  'alignment_null': False,
                  'segments_sha1': '3a3e87054939e1ecb5333ada43528c94af361620',
                  'source_index_sha1': '5b3fd9f447ce9b2d04e7238c113260a53b511ea2',
                  'spoken': ['2200원, 1000000명, 12345.67, 1,2,3 목록, 3000.']},
 'thousands_en': {'ranges': [(0, 54)],
                  'spoken_sha1': 'f19acee9343210b8833818e91fdcb8ceaed5c2fa',
                  'alignment_null': False,
                  'segments_sha1': 'f19acee9343210b8833818e91fdcb8ceaed5c2fa',
                  'source_index_sha1': 'bde233441e7281ce78de8c83adeaf1ff767dba35',
                  'spoken': ['2,200 dollars, 1,000,000 people, 12,345.67, 1,2,3 list.']},
 'stars': {'ranges': [(0, 28)],
           'spoken_sha1': 'adf8098da63ffa7e0e08b81efcddc5ca9ee69e6c',
           'alignment_null': False,
           'segments_sha1': 'e12464478315b42f68cad2ba578f7dbddb531870',
           'source_index_sha1': 'dd51e086403af59fd5113ac35d3dfff86375f4a4',
           'spoken': ['“중요” 2**3 a  b 끝.']},
 'numbered': {'ranges': [(0, 29)],
              'spoken_sha1': 'b69f6902a432c7bb95ba626e7cb72f8811955991',
              'alignment_null': False,
              'segments_sha1': 'b69f6902a432c7bb95ba626e7cb72f8811955991',
              'source_index_sha1': 'b9df61b04113527ab78ae9be2d846b02adceb7f8',
              'spoken': ['1. 첫째.\n\n2. 둘째.\n\n3) 셋째.\n\n• 불릿.\n\n* 별 불릿.']},
 'spaces': {'ranges': [(0, 11)],
            'spoken_sha1': 'e4cd7b16e8acacb818898e46c21d794ff4387d83',
            'alignment_null': False,
            'segments_sha1': 'eb0c2dc5ca7717b994d4a676bf2c5ac23d92dfd7',
            'source_index_sha1': '9ea259424afe6cf4ff029d215090a58cd650304a',
            'spoken': ['가\xa0나 다\t라\u200b마\ufeff바.']},
 'latin_edge': {'ranges': [(0, 57)],
                'spoken_sha1': 'e7cb77d27aadc7e8ee9d4c18aa6ac2637af00284',
                'alignment_null': False,
                'segments_sha1': 'e5f0031268041230cca0886e329064476c13d730',
                'source_index_sha1': 'bef0e1c5a25293d3cba6b2e4440295b1e9a06f8c',
                'spoken': ["café read me résumé naïve RÉSUMÉ config dot json user's user's."]},
 'mixed_en_punctuator': {'ranges': [(0, 60)],
                         'spoken_sha1': 'e381525e3776d83d87f696fcff1979abd5b23351',
                         'alignment_null': False,
                         'segments_sha1': 'e381525e3776d83d87f696fcff1979abd5b23351',
                         'source_index_sha1': '751b97c0770c98628bcfbcc826c78450d01e6332',
                         'spoken': ['Dr. Kim met Mr. Lee at 3 p.m. 그리고 회의를 했다. U.S. Inc. results.']},
 'long_ko': {'ranges': [(0, 2), (3, 806), (806, 902), (903, 905)],
             'spoken_sha1': 'a0977ea41d68d532933fbc068fd0d129b3ea3665',
             'alignment_null': False,
             'segments_sha1': 'a0977ea41d68d532933fbc068fd0d129b3ea3665',
             'source_index_sha1': 'aee7a5b12210ffc9bca5b38e36ad6c762db84516'},
 'long_ko_sentences': {'ranges': [(0, 736), (736, 800)],
                       'spoken_sha1': '3029286fd7628819fe19f2cb3f0b765eeed40d78',
                       'alignment_null': False,
                       'segments_sha1': '3029286fd7628819fe19f2cb3f0b765eeed40d78',
                       'source_index_sha1': '09caa022018efce761b6c9a2f694f5f8f618aaee'},
 'long_en': {'ranges': [(0, 744), (744, 930)],
             'spoken_sha1': '2c039df6e3635d1dc23209a72a4e64de965b42e4',
             'alignment_null': False,
             'segments_sha1': '2c039df6e3635d1dc23209a72a4e64de965b42e4',
             'source_index_sha1': '1bafe6e066d8c9aab862f8d2b9d5101ca1307696'},
 'long_nospace': {'ranges': [(0, 801)],
                  'spoken_sha1': '05c6bec39eca1421ffb628c672360eebb2989237',
                  'alignment_null': False,
                  'segments_sha1': '05c6bec39eca1421ffb628c672360eebb2989237',
                  'source_index_sha1': '747ca0ffff2767950564f29a747763fedfd123fa',
                  'spoken': ['가가가끝.']},
 'long_nospace_en': {'ranges': [(0, 3)],
                     'spoken_sha1': '4063bf652a2c8c0e9cfeadab8146e392c53983fa',
                     'alignment_null': False,
                     'segments_sha1': '4063bf652a2c8c0e9cfeadab8146e392c53983fa',
                     'source_index_sha1': '9fcee6eafe440c8997af1e1c1013a706fc9e5d02',
                     'spoken': ['xxx.']},
 'long_emoji_nospace': {'ranges': [(0, 500), (500, 600)],
                        'spoken_sha1': '16b2f5ce51f527caf8c7ba03665a6021f3eb8f5f',
                        'alignment_null': False,
                        'segments_sha1': '16b2f5ce51f527caf8c7ba03665a6021f3eb8f5f',
                        'source_index_sha1': '5053c71678db72d02cb72b2574b6fba8ed29ed92'},
 'empty': {'ranges': [],
           'spoken_sha1': 'da39a3ee5e6b4b0d3255bfef95601890afd80709',
           'alignment_null': False,
           'segments_sha1': 'da39a3ee5e6b4b0d3255bfef95601890afd80709',
           'source_index_sha1': '97d170e1550eee4afc0af065b78cda302a97674c',
           'spoken': []},
 'only_spaces': {'ranges': [(0, 3)],
                 'spoken_sha1': '088fb1a4ab057f4fcf7d487006499060c7fe5773',
                 'alignment_null': False,
                 'segments_sha1': '088fb1a4ab057f4fcf7d487006499060c7fe5773',
                 'source_index_sha1': '7b60211ff3e1ee1a3e68e2ac0bf3ce33f5d36b55',
                 'spoken': ['   ']},
 'only_newlines': {'ranges': [None],
                   'spoken_sha1': '71853c6197a6a7f222db0f1978c7cb232b87c5ee',
                   'alignment_null': False,
                   'segments_sha1': '71853c6197a6a7f222db0f1978c7cb232b87c5ee',
                   'source_index_sha1': '82529793c0eb954a5e89f62a6e303d16a1f24bef',
                   'spoken': ['\n\n']},
 'no_words': {'ranges': [(0, 56)],
              'spoken_sha1': '8d02e0387a3517e520f9eb4a72f83d79d96b6e8e',
              'alignment_null': False,
              'segments_sha1': '8d02e0387a3517e520f9eb4a72f83d79d96b6e8e',
              'source_index_sha1': '8f0ce1944a0cf79f3c7a29e73eda960706d01988',
              'spoken': ['README and CHANGELOG, alignSegmentsToSource, DO NOT EDIT.']},
 'latin_leading_slash_quirk': {'ranges': [None, None, None, None],
                               'spoken_sha1': 'e632546054832367fe191ed171fda0ce94320641',
                               'alignment_null': True,
                               'segments_sha1': 'e632546054832367fe191ed171fda0ce94320641',
                               'source_index_sha1': 'eafca5afcf569e1136c80c4f401f4d63f0e07cd7'},
 'ko_two_capitals': {'ranges': [(0, 71)],
                     'spoken_sha1': '2a255885649dba6f27455b8e782b1991ec9c2f7f',
                     'alignment_null': False,
                     'segments_sha1': '0b369b3fc5f0dc2e5a1c804dd487a3fd082ae33b',
                     'source_index_sha1': '8a6392ae2dadfa6f00a175634acbe233cc8310bb',
                     'spoken': ['V S Code 와 PCs, IDs, U I, U X, TCP, I P, GPT-4, js 파일, x.js, O K 쩜 U I, A I '
                                '가 I T 를.']},
 'en_two_capitals': {'ranges': [(0, 75)],
                     'spoken_sha1': '6fe2f9ae18bad6e2d0f45e14cd6c39030319402c',
                     'alignment_null': False,
                     'segments_sha1': '11d3d51a31f3d43f23c5ea4cc4fed36b584ff63c',
                     'source_index_sha1': '1fbde18a23d72127f4d71c963d436de7eeb2b939',
                     'spoken': ['VS Code and PCs, IDs, UI, UX, TCP, IP, GPT-4, js file, x.js, OK dot UI, AI '
                                'and IT.']},
 'combining_marks': {'ranges': [(0, 30)],
                     'spoken_sha1': 'b9497021101ac568697259efaf71fb14bc715efc',
                     'alignment_null': False,
                     'segments_sha1': '2e3152df0fc1d80452920493543619e4d5458499',
                     'source_index_sha1': '665af9aa3fe769c3a0601da17ca30f0623961f13',
                     'spoken': ['café R ÉSUMÉ á́́ 각각 끝.']},
 'zwj_flags': {'ranges': [(0, 36)],
               'spoken_sha1': 'd3575eff7c8b6de57e9f27c4e477366cab4a5e3b',
               'alignment_null': False,
               'segments_sha1': 'd3575eff7c8b6de57e9f27c4e477366cab4a5e3b',
               'source_index_sha1': '382bd565cfc16ce40bf71d18ba0b9f8552a5d845',
               'spoken': ['👨\u200d👩\u200d👧\u200d👦 가족 🇰🇷🇰🇷 국기 1️⃣ 첫째 👍🏽👍🏽👍🏽👍🏽 끝.']},
 'cr_only_separators': {'ranges': [(0, 20)],
                        'spoken_sha1': '7618f5c8a8069669507f9dd2016e4f42941c5e8d',
                        'alignment_null': False,
                        'segments_sha1': '7618f5c8a8069669507f9dd2016e4f42941c5e8d',
                        'source_index_sha1': '9eb7356a74a8a89c25db9d969fdac048725335bd',
                        'spoken': ['첫째\r둘째\u2028셋째\u2029넷째\x0b다섯\x0c여섯.\n\n일곱.']},
 'tabs_spaces': {'ranges': [(0, 23)],
                 'spoken_sha1': 'f8f0d191304262b08ce90948eca1ff59ef529750',
                 'alignment_null': False,
                 'segments_sha1': 'f8f0d191304262b08ce90948eca1ff59ef529750',
                 'source_index_sha1': 'ec7216eec7e07c7864545345de92bec1139a2ca2',
                 'spoken': ['가\t\t\t나   다\u3000\u3000\u3000라.']},
 'exact_750_nospace': {'ranges': [(0, 750), None],
                       'spoken_sha1': 'cd732ce7360672610b636b4aaa7acc39acc66420',
                       'alignment_null': False,
                       'segments_sha1': 'cd732ce7360672610b636b4aaa7acc39acc66420',
                       'source_index_sha1': 'abe2acb6e351cfd349fa79c8e6cc0579633993c7'},
 'exact_750_nospace_ko': {'ranges': [(0, 750), None],
                          'spoken_sha1': '4367528126ba5f7650a43cb115424771f5a7b4ac',
                          'alignment_null': False,
                          'segments_sha1': '4367528126ba5f7650a43cb115424771f5a7b4ac',
                          'source_index_sha1': 'abe2acb6e351cfd349fa79c8e6cc0579633993c7'},
 'long_digits': {'ranges': [(0, 750), (750, 800)],
                 'spoken_sha1': '41b1dc812b3cb9b80c3c45335f21419fbb6bd70f',
                 'alignment_null': False,
                 'segments_sha1': '41b1dc812b3cb9b80c3c45335f21419fbb6bd70f',
                 'source_index_sha1': 'e3519f6abc118310ba93cc32c2cd895659a447b1'},
 'long_url': {'ranges': [(0, 812)],
              'spoken_sha1': '399b46158f0cecfd18e848f1ccc2f6dc076e586f',
              'alignment_null': False,
              'segments_sha1': '399b46158f0cecfd18e848f1ccc2f6dc076e586f',
              'source_index_sha1': 'ec7216eec7e07c7864545345de92bec1139a2ca2',
              'spoken': ['앞 HTTP URL. 뒤.']},
 'only_ws_variety': {'ranges': [(0, 4)],
                     'spoken_sha1': '33acc4ea72241ca03a55102e4b31543663fc9ece',
                     'alignment_null': False,
                     'segments_sha1': '33acc4ea72241ca03a55102e4b31543663fc9ece',
                     'source_index_sha1': '9fcee6eafe440c8997af1e1c1013a706fc9e5d02',
                     'spoken': [' \t\u3000\ufeff']},
 'en_long_bullet_quirk': {'ranges': [None, None, None],
                          'spoken_sha1': '9e91389a50b2577ca78b9287091a0e7e7838f11f',
                          'alignment_null': True,
                          'segments_sha1': '9e91389a50b2577ca78b9287091a0e7e7838f11f',
                          'source_index_sha1': 'b86ad379ddafbc619adb07f906e0d4673d59480d'}}


# JS 의 \s (node 로 확인한 목록)
JS_WS = frozenset("\t\n\x0b\x0c\r       　﻿"
                  + "".join(chr(c) for c in range(0x2000, 0x200B)))


def u16len(s):
    return len(s.encode("utf-16-le", "surrogatepass")) // 2


def words_of(spec):
    return {} if spec in (None, "none") else spec


def strip_ws(s):
    return "".join(c for c in s if c not in JS_WS)


class GoldenParityTest(unittest.TestCase):
    """확장 JS(HEAD) 결과와 조각 경계·원문 오프셋·읽기용 글·위치표(sourceIndex)가 같은지."""

    def test_hand_cases_match_extension(self):
        self.assertEqual(sorted(c["name"] for c in HAND_CASES), sorted(GOLDEN))
        for c in HAND_CASES:
            with self.subTest(name=c["name"]):
                expected = GOLDEN[c["name"]]
                text, lang = c["text"], c["lang"]
                voice = c.get("voiceLang") or lang
                segments = rt.build_segments(text, lang)
                seg_digest = hashlib.sha1("\x00".join(segments).encode("utf-8", "surrogatepass")).hexdigest()
                self.assertEqual(seg_digest, expected["segments_sha1"])
                alignment = rt.align_segments_to_source(text, segments)
                self.assertEqual(alignment is None, expected["alignment_null"])
                ranges = [alignment.segment_range(i) if alignment else None for i in range(len(segments))]
                self.assertEqual(ranges, expected["ranges"])
                spoken = [rt.make_spoken_text(s, voice, words_of(c["words"])) for s in segments]
                texts = [sp.text for sp in spoken]
                digest = hashlib.sha1("\x00".join(texts).encode("utf-8", "surrogatepass")).hexdigest()
                if "spoken" in expected:
                    self.assertEqual(texts, expected["spoken"])
                self.assertEqual(digest, expected["spoken_sha1"])
                src = [[sp.source_index(i) for i in range(len(sp.text) + 1)] for sp in spoken]
                self.assertEqual(hashlib.sha1(json.dumps(src).encode()).hexdigest(), expected["source_index_sha1"])

    def test_public_function_matches_parts(self):
        for c in HAND_CASES:
            with self.subTest(name=c["name"]):
                result = rt.split_for_reading(c["text"], c["lang"], c.get("voiceLang"), words_of(c["words"]))
                expected = GOLDEN[c["name"]]
                self.assertEqual([(r["src_start"], r["src_end"]) if r["src_start"] is not None else None
                                  for r in result], expected["ranges"])
                if "spoken" in expected:
                    self.assertEqual([r["text"] for r in result], expected["spoken"])

    def test_base_commit(self):
        self.assertEqual(rt.EXTENSION_BASE_COMMIT, "afae39a")


class PublicApiTest(unittest.TestCase):
    def test_shape_and_half_open_offsets(self):
        text = "첫째 줄입니다 그리고 이어지는 글이 조금 더 있습니다\n둘째 줄은 README 를 설명합니다 조금 더 길게"
        result = rt.split_for_reading(text, "ko-KR", words=MINI_WORDS)
        self.assertEqual(len(result), 2)
        for item in result:
            self.assertEqual(set(item), {"text", "src_start", "src_end"})
            self.assertIsInstance(item["src_start"], int)
            self.assertLess(item["src_start"], item["src_end"])
        self.assertEqual(text[result[0]["src_start"]:result[0]["src_end"]], text.split("\n")[0])
        self.assertEqual(text[result[1]["src_start"]:result[1]["src_end"]], text.split("\n")[1])
        self.assertIn("read me", result[1]["text"])

    def test_empty_input(self):
        self.assertEqual(rt.split_for_reading("", "ko-KR"), [])
        self.assertEqual(rt.split_for_reading(None, "ko-KR"), [])

    def test_whitespace_only_input_is_one_segment(self):
        # 확장과 같다: 공백만 있어도 조각 하나(음성에 보낼지는 호출하는 쪽이 정한다)
        for text in (" ", "   ", "\t", "　", " \t　﻿"):
            result = rt.split_for_reading(text, "ko-KR")
            self.assertEqual(result, [{"text": text, "src_start": 0, "src_end": len(text)}], repr(text))

    def test_no_source_chars_gives_none(self):
        result = rt.split_for_reading("\n\n\n", "ko-KR")
        self.assertEqual(result, [{"text": "\n\n", "src_start": None, "src_end": None}])

    def test_alignment_failure_keeps_reading(self):
        # 확장과 같은 동작: 정렬이 실패해도 조각(읽을 글)은 그대로 나오고 오프셋만 None
        result = rt.split_for_reading("첫 줄\na, /" + "word " * 160, "en-US")
        self.assertGreater(len(result), 1)
        self.assertTrue(all(r["src_start"] is None and r["src_end"] is None for r in result))
        self.assertTrue(all(r["text"] for r in result))

    def test_mismatched_segments_return_none(self):
        self.assertIsNone(rt.align_segments_to_source("abc", ["xyz"]))

    def test_emoji_offsets_are_code_points(self):
        text = "😀 가나다\n🎉 끝입니다 여기까지 읽어 주세요 조금 더 길게 씁니다 스무 글자 넘게"
        result = rt.split_for_reading(text, "ko-KR")
        self.assertEqual(result[0]["src_start"], 0)
        self.assertEqual(result[-1]["src_end"], len(text))


class LineRuleTest(unittest.TestCase):
    """player.js:81 줄 나누기, speech.js:440-497 CharBreaker(keepApart) 규칙."""

    TWENTY = "가나다라마바사아자차카타파하거너더러머버"  # 한글 20자 = 60바이트, 같은 글자 3연속 없음

    def test_line_of_60_bytes_joins_next(self):
        self.assertEqual(len(self.TWENTY.encode("utf-8")), 60)
        segments = rt.build_segments(self.TWENTY + "\n다음 줄", "ko-KR")
        self.assertEqual(len(segments), 1)

    def test_line_over_60_bytes_stands_alone(self):
        segments = rt.build_segments(self.TWENTY + "서\n다음 줄", "ko-KR")
        self.assertEqual(len(segments), 2)

    def test_closing_period_not_counted(self):
        segments = rt.build_segments(self.TWENTY + ".\n다음 줄", "ko-KR")
        self.assertEqual(len(segments), 1)

    def test_60_bytes_skip_every_js_whitespace(self):
        # 공백 종류와 상관없이 JS \s 는 안 센다(NBSP·전각 공백·탭·BOM·em space)
        spaced = "가나다라마 바사아자차　카타파하거\t너더러머﻿버 "
        self.assertEqual(len(rt.build_segments(spaced + "\n다음 줄", "ko-KR")), 1)
        self.assertEqual(len(rt.build_segments(spaced + "서\n다음 줄", "ko-KR")), 2)

    def test_60_bytes_count_zero_width_space(self):
        # U+200B 는 JS \s 가 아니다 → 3바이트로 센다
        self.assertEqual(len(rt.build_segments(self.TWENTY[:19] + "​\n다음 줄", "ko-KR")), 1)   # 57+3=60
        self.assertEqual(len(rt.build_segments(self.TWENTY + "​\n다음 줄", "ko-KR")), 2)        # 63

    def test_60_bytes_emoji_is_4_bytes(self):
        fifteen = "😀🎉😀🎉😀🎉😀🎉😀🎉😀🎉😀🎉😀"  # 15 x 4 = 60바이트(반복 아님)
        self.assertEqual(len(fifteen.encode("utf-8")), 60)
        self.assertEqual(len(rt.build_segments(fifteen + "\n다음", "ko-KR")), 1)
        self.assertEqual(len(rt.build_segments(fifteen + "가\n다음", "ko-KR")), 2)

    def test_750_is_utf16_length_not_bytes_or_code_points(self):
        # 줄 끝 '.' 까지 750(UTF-16) 이하면 한 조각
        self.assertEqual(len(rt.build_segments("ab" * 374 + "a", "en-US")), 1)          # 749 + '.'
        self.assertEqual(rt.build_segments("ab" * 375, "en-US"), ["ab" * 375, "."])     # 750 + '.'
        # 바이트가 아니다: 한글 749자(2247바이트)도 한 조각
        self.assertEqual(len(rt.build_segments("가나" * 374 + "가", "ko-KR")), 1)
        # 코드 포인트가 아니다: 이모지는 2로 센다. 499글자 = 749(UTF-16) + '.' → 한 조각, 500글자 = 750 → 두 조각
        self.assertEqual(len(rt.build_segments("😀가" * 249 + "😀", "ko-KR")), 1)
        self.assertEqual(len(rt.build_segments("😀가" * 250, "ko-KR")), 2)

    def test_split_priority_sentence_phrase_word_char(self):
        # 750 을 넘을 때만 더 잘게: 문장 → 구 → 단어 → 글자
        sentences = rt.build_segments("이것은 아주 긴 문장입니다. " * 50, "ko-KR")
        self.assertTrue(all(s.endswith(". ") for s in sentences[:-1]), sentences)
        phrases = rt.build_segments("The quick brown fox jumps over the lazy dog, again and again; " * 15, "en-US")
        self.assertTrue(all(s.endswith((", ", "; ")) for s in phrases[:-1]))
        words = rt.build_segments("word " * 200, "en-US")
        self.assertTrue(all(s.endswith(" ") for s in words[:-1]))
        self.assertTrue(all(u16len(s) <= rt.CHAR_LIMIT for s in words))
        chars = rt.build_segments("abcdefghij" * 100, "en-US")
        self.assertEqual([len(s) for s in chars], [750, 251])

    def test_every_line_split_at_line_breaks(self):
        lines = rt.split_lines("  가  \r\n\n  나\n다")
        self.assertEqual(lines, [("  가", 0), ("나", 10), ("다", 12)])

    def test_only_newline_breaks_lines(self):
        # /\s*\r?\n\s*/ — \r 단독, U+2028, U+2029, VT, FF 는 줄을 나누지 않는다
        for sep in ("\r", " ", " ", "\x0b", "\x0c"):
            self.assertEqual(len(rt.split_lines("가" + sep + "나")), 1, repr(sep))
        self.assertEqual(rt.split_lines("가 \t\r\n　나"), [("가", 0), ("나", 6)])

    def test_segments_within_750_utf16(self):
        for text, lang in ((LONG_KO, "ko-KR"), (LONG_EN, "en-US"), ("x " * 2000, "en-US"),
                           ("가" + "😀" * 400, "ko-KR"), ("😀가" * 400, "ko-KR"), ("abcdefghij" * 300, "ko-KR")):
            for seg in rt.build_segments(text, lang):
                self.assertLessEqual(u16len(seg), rt.CHAR_LIMIT)

    def test_no_lone_surrogates(self):
        # 알려진 차이: JS 는 750(UTF-16)자 경계에서 이모지 쌍을 쪼갤 수 있다. 파이썬은 글자를 쪼개지 않는다
        for text in ("가" + "😀" * 400, "가😀" * 400, "a" + "😀b" * 400):
            for lang in ("ko-KR", "en-US"):
                for seg in rt.build_segments(text, lang):
                    self.assertFalse(any(0xD800 <= ord(c) <= 0xDFFF for c in seg))

    def test_needs_period(self):
        self.assertTrue(rt.needs_period("가나다"))
        self.assertTrue(rt.needs_period("끝😀"))
        for done in ("끝.", "끝!", "끝?", "끝,", "끝;", "끝:", "끝…", "끝。", "끝！", "끝？", "끝、", "끝，", "끝；",
                     "끝：", "끝 ", "끝　", "끝\n", ""):
            self.assertFalse(rt.needs_period(done), done)
        # JS 의 \s 가 아닌 글자(파이썬 isspace 는 참): 마침표를 붙인다
        for not_js_space in ("\x1c", "\x85", "᠎", "​"):
            self.assertTrue(rt.needs_period("끝" + not_js_space), repr(not_js_space))

    def test_east_asian_rule(self):
        self.assertTrue(rt.is_east_asian("ko-KR"))
        self.assertTrue(rt.is_east_asian("ja-JP"))
        self.assertTrue(rt.is_east_asian("zh-CN"))
        self.assertFalse(rt.is_east_asian("en-US"))
        self.assertFalse(rt.is_east_asian(None))
        # /^zh|ko|ja/ 의 우선순위 버릇까지 확장과 같다
        self.assertTrue(rt.is_east_asian("x-ko"))
        self.assertFalse(rt.is_east_asian("x-zh"))


class PreprocessTest(unittest.TestCase):
    def test_repeated_chars(self):
        self.assertEqual(rt.truncate_repeated_chars("ㅋㅋㅋㅋㅋ!!!!!", 3), "ㅋㅋㅋ!!!")
        self.assertEqual(rt.truncate_repeated_chars("1111111", 3), "1111111")
        # 이모지는 JS(UTF-16 비교)처럼 반복으로 치지 않는다
        self.assertEqual(rt.truncate_repeated_chars("😀😀😀😀😀", 3), "😀😀😀😀😀")
        # 공백·결합 문자도 같은 규칙
        self.assertEqual(rt.truncate_repeated_chars("a     b\t\t\t\tc", 3), "a   b\t\t\tc")
        self.assertEqual(rt.truncate_repeated_chars("á́́́", 3), "á́́")

    def test_repeated_chars_tracked_offsets(self):
        text, src = rt.truncate_repeated_chars_tracked("aaaaab", list(range(6)), 3)
        self.assertEqual(text, "aaab")
        self.assertEqual(src, [0, 1, 2, 5])

    def test_url(self):
        self.assertEqual(rt.preprocess("보기 https://a.b/c?d=1 끝"), "보기 HTTP URL. 끝")
        text, src = rt.replace_urls_tracked("x http://a.b y", list(range(14)))
        self.assertEqual(text, "x HTTP URL. y")
        self.assertEqual(src[2], 2)       # 첫 글자 = URL 시작
        self.assertEqual(src[10], 11)     # 끝 글자 = URL 마지막 글자
        self.assertEqual(src[3:10], [-1] * 7)


class SourceOffsetTest(unittest.TestCase):
    """지운 글자·바꾼 글자·끼워 넣은 글자에서 원문 위치가 어떻게 움직이는지."""

    def test_deleted_repeats_fall_outside_range(self):
        # "끝!!!!!" → "끝!!!." : 남은 글자만 원문을 가리키므로 끝의 "!!" 는 구간 밖
        al = rt.align_segments_to_source("끝!!!!!", rt.build_segments("끝!!!!!", "ko-KR"))
        self.assertEqual(al.segment_range(0), (0, 4))

    def test_url_range_covers_whole_url(self):
        text = "보기 https://a.b/c 끝"
        segments = rt.build_segments(text, "ko-KR")
        al = rt.align_segments_to_source(text, segments)
        self.assertEqual(al.segment_range(0), (0, len(text)))
        start = segments[0].index("HTTP")
        self.assertEqual(al.word_range(0, start), (3, 4))                  # "HTTP" → URL 첫 글자
        url_end = text.index(" 끝")
        url_at = segments[0].index("URL.")
        self.assertIsNone(al.word_range(0, url_at))                          # "URL" 은 모두 끼운 글자
        self.assertEqual(al.word_range(0, url_at, 4), (url_end - 1, url_end))  # "." → URL 끝 글자

    def test_inserted_period_and_joiner_have_no_source(self):
        text = "가나\n다라"
        segments = rt.build_segments(text, "ko-KR")
        self.assertEqual(segments, ["가나.\n\n다라."])
        al = rt.align_segments_to_source(text, segments)
        self.assertEqual(al.maps[0], [0, 1, -1, -1, -1, 3, 4, -1])

    def test_spoken_deletions(self):
        sp = rt.make_spoken_text("**굵게** 2,200", "ko-KR", MINI_WORDS)
        self.assertEqual(sp.text, "굵게 2200")
        self.assertEqual([sp.source_index(i) for i in range(len(sp.text) + 1)], [2, 3, 6, 7, 9, 10, 11, 12])

    def test_spoken_replacements_and_insertions(self):
        sp = rt.make_spoken_text("가 → 나", "ko-KR", MINI_WORDS)
        self.assertEqual(sp.text, "가. 나")
        self.assertEqual([sp.source_index(i) for i in range(len(sp.text) + 1)], [0, 2, 2, 4, 5])
        sp = rt.make_spoken_text("VS", "ko-KR", MINI_WORDS)   # afae39a: 두 글자 대문자는 떼어 읽힌다
        self.assertEqual(sp.text, "V S")
        self.assertEqual([sp.source_index(i) for i in range(4)], [0, 1, 1, 2])
        sp = rt.make_spoken_text("a.js", "ko-KR", MINI_WORDS)
        self.assertEqual(sp.text, "a.js")                        # 한 글자 옆 기호는 말하지 않는다

    def test_source_index_out_of_range(self):
        sp = rt.make_spoken_text("README", "en-US", MINI_WORDS)
        self.assertEqual(sp.source_index(-1), len("README"))
        self.assertEqual(sp.source_index(len(sp.text) + 5), len("README"))


# ── 불변식(적대적 입력) ────────────────────────────────────────────────
FUZZ_FRAGMENTS = [
    "가", "나다", "한국어", "문장입니다.", "a", "The", "quick", "README", "VS", "Code", "PCs", "IDs", "UI/UX", "TCP/IP",
    "GPT-4", "js", "x.js", "ok.ui", "page-ui-host.js", "node_modules", "/usr/bin", "~/.ssh", "./run.sh",
    "café", "RÉSUMÉ", "á́́́́", "각",
    "👨‍👩‍👧‍👦", "🇰🇷🇰🇷", "1️⃣", "👍🏽", "😀", "😀😀😀😀", "❤️", "𝒜𝒷𝒸", "→", "→→→→", "->", "-->", "⇒",
    "**", "***", "*", "/", " / ", "—", "-----", "=====", ".....", "!!!!!", "ㅋㅋㅋㅋㅋ", "aaaaaa", "1111111", "2,200",
    "1,000,000", "1,2,3", "https://example.com/a/b?c=1", "http://x.y/z", "https://t.co/😀", "httpsss://no",
    "hhhhttp://x.y", "abcdefghij" * 90, "가나다라" * 200, "1234567890" * 80, "😀가" * 400, "a," * 400, "가." * 400,
    "- " + "word " * 160, "(", ")", "[x]", "“", "”", "'", "\"", "`", "Dr.", "U.S.", "e.g.", "Inc.", ",", ";", ":",
    "…", "。", "，", "、", "​", "﻿", " ", " ", "　", " ", " ", "\x0b", "\x0c", "\r",
]
FUZZ_SEPARATORS = [" ", " ", "", "\n", "\r\n", "\n\n", "\t", "  ", "     ", "\n \t\n", "\r", "　", " ",
                   "\n \n"]
EDGE_TEXTS = [
    "", " ", "   ", "\t", "\n", "\r\n", "\r", "\n\n\n", " \n \n ", "　", "﻿", "​", ".", "。", "😀",
    "👨‍👩‍👧‍👦", "́", "á", "x" * 800, "ab" * 400, "가나" * 400, "😀" * 400, "😀가" * 400,
    "가" + "😀" * 400, "https://" + "ab" * 400, "a" * 3000, "12" * 400, "/" + "word " * 200, "a, /" + "word " * 200,
]


def _dropped_repeat_or_url_positions(text):
    """정렬표에 없어도 되는 원문 위치: 줄 안에서 같은 글자 4번째부터(반복 줄임), URL 안쪽(HTTP URL. 로 바뀜)."""
    import re
    url = re.compile(r"https?://[^\t\n\x0b\x0c\r    -     　﻿]+")
    exempt = set()
    for line, base in rt.split_lines(text):
        run = 1
        for i in range(1, len(line)):
            c = line[i]
            if c == line[i - 1] and ord(c) <= 0xFFFF and not ("0" <= c <= "9"):
                run += 1
                if run > 3:
                    exempt.add(base + i)
            else:
                run = 1
        for m in url.finditer(line):
            exempt.update(range(base + m.start(), base + m.end()))
    return exempt


def _joined(text):
    parts = []
    for line, _ in rt.split_lines(text):
        line = rt.preprocess(line)
        parts.append(line + "." if rt.needs_period(line) else line)
    return "\n\n".join(parts)


class InvariantTest(unittest.TestCase):
    """모든 조각의 원문 구간이 원문 안에 있고, 서로 겹치지 않고, 순서대로이며, 빠진 글자가 없는지."""

    def check(self, text, lang, voice, words):
        segments = rt.build_segments(text, lang)
        for seg in segments:
            self.assertLessEqual(u16len(seg), rt.CHAR_LIMIT)
            self.assertFalse(any(0xD800 <= ord(c) <= 0xDFFF for c in seg))
        al = rt.align_segments_to_source(text, segments)
        # 정렬 실패(None)는 조각 나누기가 공백 아닌 글자를 떨어뜨렸을 때뿐이다(확장 버릇 (a): 머리의 - / —)
        dropped = bool(segments) and strip_ws("".join(segments)) != strip_ws(_joined(text))
        self.assertEqual(al is None, dropped)
        if al is not None:
            prev_end = 0
            covered = set()
            for i, seg in enumerate(segments):
                r = al.segment_range(i)
                if r is None:
                    # 원문 글자가 없는 조각: 공백뿐이거나, 750자 딱 맞는 공백 없는 줄에 붙인 마침표 하나
                    self.assertIn(strip_ws(seg), ("", "."))
                    continue
                start, end = r
                self.assertTrue(0 <= start < end <= len(text), r)
                self.assertGreaterEqual(start, prev_end)          # 겹치지 않고 순서대로
                prev_end = end
                covered.update(range(start, end))
            exempt = _dropped_repeat_or_url_positions(text)
            missing = [p for p, c in enumerate(text) if c not in JS_WS and p not in covered and p not in exempt]
            self.assertEqual(missing, [])
        result = rt.split_for_reading(text, lang, voice, words)
        self.assertEqual(len(result), len(segments))
        for i, seg in enumerate(segments):
            sp = rt.make_spoken_text(seg, voice or lang, words)
            self.assertEqual(result[i]["text"], sp.text)
            self.assertEqual(len(sp.src), len(sp.text))
            self.assertTrue(all(0 <= v < len(seg) for v in sp.src))
            self.assertTrue(all(sp.src[k] <= sp.src[k + 1] for k in range(len(sp.src) - 1)))
            self.assertEqual(sp.source_index(len(sp.text)), len(seg))
            span = al.segment_range(i) if al is not None else None
            self.assertEqual((result[i]["src_start"], result[i]["src_end"]), span if span else (None, None))

    def test_edge_texts(self):
        for text in EDGE_TEXTS:
            for lang in ("ko-KR", "en-US", "ja-JP"):
                with self.subTest(text=text[:20], lang=lang):
                    self.check(text, lang, None, MINI_WORDS)

    def test_random_adversarial_texts(self):
        rng = random.Random(20260928)
        for n in range(250):
            parts = []
            for _ in range(rng.choice([1, 2, 5, 15, 40, 120])):
                parts.append(rng.choice(FUZZ_FRAGMENTS))
                parts.append(rng.choice(FUZZ_SEPARATORS))
            if rng.random() < 0.5:
                parts.pop()
            text = "".join(parts)
            lang = rng.choice(["ko-KR", "en-US", "ja-JP", "zh-CN"])
            voice = rng.choice([None, "ko-KR", "en-US"])
            with self.subTest(n=n, text=text[:40], lang=lang, voice=voice):
                self.check(text, lang, voice, rng.choice([None, MINI_WORDS]))


class SpokenTextTest(unittest.TestCase):
    def spoken(self, text, lang="ko-KR", words=MINI_WORDS):
        return rt.make_spoken_text(text, lang, words).text

    def test_capital_words(self):
        self.assertEqual(self.spoken("README CHANGELOG API", "en-US"), "read me change log API")
        self.assertEqual(self.spoken("DO NOT EDIT", "en-US"), "do not edit")

    def test_code_names(self):
        self.assertEqual(self.spoken("page-ui-host.js"), "page 대시 U I 대시 host 쩜 J S")
        self.assertEqual(self.spoken("page-ui-host.js", "en-US"), "page dash UI dash host dot JS")
        self.assertEqual(self.spoken("node_modules", "en-US"), "node underscore modules")
        self.assertEqual(self.spoken("alignSegmentsToSource"), "align Segments To Source")
        self.assertEqual(self.spoken("GPT-4 v2.0 Wi-Fi"), "GPT-4 v2.0 Wi-Fi")

    def test_two_capitals_korean_voice(self):
        # afae39a (spoken-text.js:165-171, 248-255, 266): 한국어 음성만 "V S"
        self.assertEqual(self.spoken("VS Code"), "V S Code")
        self.assertEqual(self.spoken("VS Code", "en-US"), "VS Code")
        self.assertEqual(self.spoken("UI/UX TCP/IP"), "U I, U X TCP, I P")
        self.assertEqual(self.spoken("PCs IDs APIs", "ko-KR"), "PCs IDs APIs")
        self.assertEqual(self.spoken("DO NOT EDIT"), "do not edit")   # 대문자 문장 안의 짧은 단어는 그대로 단어

    def test_marks(self):
        self.assertEqual(self.spoken("동남아 → 일본"), "동남아. 일본")
        self.assertEqual(self.spoken("알류샨/알래스카"), "알류샨, 알래스카")
        self.assertEqual(self.spoken("9/27 2**3"), "9/27 2**3")
        self.assertEqual(self.spoken("**“굵게”**"), "“굵게”")

    def test_thousands_only_for_korean(self):
        self.assertEqual(self.spoken("2,200 1,2,3"), "2200 1,2,3")
        self.assertEqual(self.spoken("2,200 1,2,3", "en-US"), "2,200 1,2,3")

    def test_other_languages_untouched(self):
        self.assertEqual(self.spoken("README → x", "ja-JP"), "README → x")

    def test_without_word_list(self):
        self.assertEqual(rt.make_spoken_text("README", "en-US").text, "README")

    def test_source_index(self):
        sp = rt.make_spoken_text("README.md", "ko-KR", MINI_WORDS)
        self.assertEqual(sp.text, "read me 쩜 M D")
        self.assertEqual(sp.source_index(0), 0)
        self.assertEqual(sp.source_index(5), 4)            # "me" 의 m ← README 의 M
        self.assertEqual(sp.source_index(len(sp.text)), len("README.md"))

    def test_fallback_on_error(self):
        # 잘못된 단어 목록 → README 를 찾다가 변환 실패 → 글을 그대로 (speech.js:104-113)
        sp = rt.spoken_text("README", "ko-KR", words=object())
        self.assertEqual(sp.text, "README")
        self.assertEqual(sp.source_index(2), 2)


class WordRangeTest(unittest.TestCase):
    def test_word_range(self):
        text = "안녕하세요 여러분 반갑습니다 오늘은 좋은 날입니다 모두 행복하세요"
        segments = rt.build_segments(text, "ko-KR")
        al = rt.align_segments_to_source(text, segments)
        start = segments[0].index("여러분")
        self.assertEqual(al.word_range(0, start), (start, start + 3))
        self.assertEqual(al.word_range(0, start, 2), (start, start + 2))
        self.assertIsNone(al.word_range(0, len(segments[0])))
        self.assertIsNone(al.word_range(0, -1))
        self.assertIsNone(al.word_range(5, 0))
        self.assertIsNone(al.segment_range(-1))


class PausesMarkupTest(unittest.TestCase):
    def test_markup(self):
        self.assertEqual(rt.pauses_markup("가, 나. 다 [x]", "ko-KR", "Chirp3-HD"),
                         "가, [pause short] 나. [pause] 다 (x)")
        self.assertIsNone(rt.pauses_markup("가, 나", "en-US", "Chirp3-HD"))
        self.assertIsNone(rt.pauses_markup("가, 나", "ko-KR", "Neural2"))
        self.assertIsNone(rt.pauses_markup("가나다", "ko-KR", "Chirp3-HD"))


class EnglishWordsLoaderTest(unittest.TestCase):
    def test_load_extension_format(self):
        content = ('/*\n * header "not words"\n */\nconst englishWords = (() => {\n  const levels = {\n'
                   '    10: "a read me",\n    35: "log read",\n  }\n})()\n')
        with tempfile.TemporaryDirectory() as tmp:
            path = os.path.join(tmp, "english-words.js")
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            words = rt.load_english_words(path)
        self.assertEqual(words, {"a": 10, "read": 35, "me": 10, "log": 35})


if __name__ == "__main__":
    unittest.main()
